name: Desplegar Aplicacion Rock And Gol

on:
  push:
    branches:
      - master-rockandgol

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo fuente
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Hacer el build de la aplicacion
        run: npm run build

      - name: Sincronizar archivos con el servidor
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}

          SOURCE: 'dist/'
          TARGET: "/home/complejorockandgol.com.ar/public_html"
          ARGS: "--delete"
          EXCLUDE: ".htaccess"